blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/sky-flux/flux/discussions
    about: Ask questions and get help from the community. Please don't open issues for support requests.
